### PR TITLE
fix: fixed irating change in relative

### LINKED ISSUE #321: Irating change does not work in relative
Irating change does not work in relative
In standings, appears the value, but not in the relative

### PR DESCRIPTION
**Pull request by spikethedog78**
## Description

Fixed display of iRating change in relatives

## Before

image

## After

image

## Type of Change

- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Performance improvement
- [ ] Refactoring (no functional changes)
- [ ] Documentation update
- [ ] Dependency update

## Checklist

- [ ] I have discussed this change in the discord server
- [ ] I have tested this in iRacing (either in an online session or with AI)
- [X] All tests pass locally via `npm test`
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] I have run `npm run lint` and fixed any issues
- [X] I have performed a self-review of my own code
- [ ] I have added/updated Storybook stories for visual changes
- [ ] I have updated the README.md (if applicable)
- [ ] I have updated defaultDashboard.ts if introducing new widgets or configurations (if applicable)

### CODE REVIEW

File: src/frontend/components/Standings/hooks/useDriverPositions.tsx [hunk 1]
```diff
@@ -282,7 +284,17 @@ export const useDriverStandings = () => {
...
+      .filter((s) => !!s)
+      .sort((a, b) => a.position - b.position);
+
+    if (sessionType !== 'Race' || !isOfficial) {
+      return filteredStandings;
+    }
+
+    return augmentStandingsWithIRating(groupStandingsByClass(filteredStandings))
+      .flatMap(([, classStandings]) => classStandings)
+      .sort((a, b) => (a?.position ?? 0) - (b?.position ?? 0));
```
Comment (tariknz) [inline src/frontend/components/Standings/hooks/useDriverPositions.tsx:297]: I suggest separately we actually split this memo up because this is going to recalculate pretty often when it doesn't need to.

Would consider its own hook e.g. useIRatingChanges(standings)

**Review by tariknz — APPROVED** [review]
